version: "3"

services: 
    postgres_db:
        image: postgres:latest
        container_name: postgres-kikoya
        environment:
            POSTGRES_USER: kikoyo_user
            POSTGRES_DB: kikoya_db
            POSTGRES_PASSWORD: kikoya_!!!
        ports:
            - "5432:5432"
        restart: always
        volumes:  
                - ./dump.sql:/docker-entrypoint-initdb.d/kikoya.sql

